- name: 紹介
  url: ./introduction.md
- name: はじめに
  content:
    - name: スクリプト参照
      url: ./script-reference.md
    - name: 最初のアプリを作成する
      url: ./create-first-app.md
- name: クイックスタート
  url: ./quick-start.md
- name: テンプレート構文
  content:
    - name: コンテンツレンダリング
      url: ./content-rendering.md
    - name: イベントバインディング
      url: ./event-binding.md
    - name: 属性リアクティブ
      url: ./property-response.md
    - name: 属性バインディング
      url: ./property-binding.md
    - name: クラスとスタイルのバインディング
      url: ./class-style-binding.md
    - name: 条件付きレンダリング
      url: ./conditional-rendering.md
    - name: リストレンダリング
      url: ./list-rendering.md
    - name: 算出プロパティ
      url: ./computed-properties.md
    - name: ウォッチャー
      url: ./watchers.md
    - name: ライフサイクル
      url: ./lifecycle.md
- name: コンポーネント
  content:
    - name: コンポーネントの作成
      url: ./create-component.md
    - name: 属性の継承
      url: ./inherit-attributes.md
    - name: スロット
      url: ./slots.md
    - name: ディーププロパティバインディング
      url: ./deep-property-binding.md
    - name: カスタムイベント
      url: ./custom-events.md
- name: アプリとスケーリング
  content:
    - name: マイクロアプリ
      url: ./micro-app.md
    - name: アプリ設定の基本
      url: ./app-config-basics.md
    - name: ページトランジションアニメーション
      url: ./page-transition-animation.md
    - name: 読み込みとエラーハンドリング
      url: ./app-loading-error.md
    - name: アプリ初期化
      url: ./app-initialization.md
    - name: ルーティングとナビゲーション
      url: ./app-navigation.md
    - name: シングルページアプリケーション
      url: ./routes.md
    - name: ネストされたルート
      url: ./nested-routes.md
    - name: SSRと同型レンダリング
      url: ./ssr.md
- name: 状態管理
  content:
    - name: 状態管理とは
      url: ./state-management.md
    - name: コンテキスト状態
      url: ./context-state.md
    - name: スタイルクエリ
      url: ./match-var.md
- name: 本番環境とデプロイ
  url: ./build-app.md
- name: その他のコンポーネント
  content:
    - name: ホストスタイルの注入
      url: ./inject-host-style.md
    - name: 非明示的コンポーネント
      url: ./non-explicit-component.md
    - name: replace-temp コンポーネント
      url: ./replace-template.md