- name: Introducción
  url: ./introduction.md
- name: Primeros pasos
  content:
    - name: Referencia del script
      url: ./script-reference.md
    - name: Crear la primera aplicación
      url: ./create-first-app.md
- name: Inicio rápido
  url: ./quick-start.md
- name: Sintaxis de plantillas
  content:
    - name: Renderizado de contenido
      url: ./content-rendering.md
    - name: Vinculación de eventos
      url: ./event-binding.md
    - name: Reactividad de propiedades
      url: ./property-response.md
    - name: Vinculación de propiedades
      url: ./property-binding.md
    - name: Vinculación de clases y estilos
      url: ./class-style-binding.md
    - name: Renderizado condicional
      url: ./conditional-rendering.md
    - name: Renderizado de listas
      url: ./list-rendering.md
    - name: Propiedades computadas
      url: ./computed-properties.md
    - name: Observadores
      url: ./watchers.md
    - name: Ciclo de vida
      url: ./lifecycle.md
- name: Componentes
  content:
    - name: Crear un componente
      url: ./create-component.md
    - name: Pasar atributos heredables
      url: ./inherit-attributes.md
    - name: Ranuras
      url: ./slots.md
    - name: Vinculación de propiedades profundas
      url: ./deep-property-binding.md
    - name: Eventos personalizados
      url: ./custom-events.md
- name: Aplicación y escalado
  content:
    - name: Microaplicaciones
      url: ./micro-app.md
    - name: Configuración básica de la app
      url: ./app-config-basics.md
    - name: Animación de transición de página
      url: ./page-transition-animation.md
    - name: Carga y manejo de errores
      url: ./app-loading-error.md
    - name: Inicialización de la app
      url: ./app-initialization.md
    - name: Rutas y navegación
      url: ./app-navigation.md
    - name: Aplicación de una sola página
      url: ./routes.md
    - name: Rutas anidadas
      url: ./nested-routes.md
    - name: SSR y renderizado isomórfico
      url: ./ssr.md
- name: Gestión de estado
  content:
    - name: ¿Qué es la gestión de estado?
      url: ./state-management.md
    - name: Estado de contexto
      url: ./context-state.md
    - name: Consulta de estilos
      url: ./match-var.md
- name: Producción y despliegue
  url: ./build-app.md
- name: Otros componentes
  content:
    - name: Inyección de estilos del host
      url: ./inject-host-style.md
    - name: Componente no explícito
      url: ./non-explicit-component.md
    - name: Componente replace-temp
      url: ./replace-template.md