- name: Introduction
  url: ./introduction.md
- name: Premiers pas
  content:
    - name: Référence du script
      url: ./script-reference.md
    - name: Créer la première application
      url: ./create-first-app.md
- name: Démarrage rapide
  url: ./quick-start.md
- name: Syntaxe du template
  content:
    - name: Rendu du contenu
      url: ./content-rendering.md
    - name: Liaison d'événements
      url: ./event-binding.md
    - name: Réactivité des propriétés
      url: ./property-response.md
    - name: Liaison de propriétés
      url: ./property-binding.md
    - name: Liaison de classes et styles
      url: ./class-style-binding.md
    - name: Rendu conditionnel
      url: ./conditional-rendering.md
    - name: Rendu de liste
      url: ./list-rendering.md
    - name: Propriétés calculées
      url: ./computed-properties.md
    - name: Observateurs
      url: ./watchers.md
    - name: Cycle de vie
      url: ./lifecycle.md
- name: Composants
  content:
    - name: Créer un composant
      url: ./create-component.md
    - name: Transmission d'attributs de caractéristiques
      url: ./inherit-attributes.md
    - name: Slots
      url: ./slots.md
    - name: Liaison de propriétés profondes
      url: ./deep-property-binding.md
    - name: Événements personnalisés
      url: ./custom-events.md
- name: Application et mise à l'échelle
  content:
    - name: Micro-application
      url: ./micro-app.md
    - name: Bases de configuration d'application
      url: ./app-config-basics.md
    - name: Animation de transition de page
      url: ./page-transition-animation.md
    - name: Gestion du chargement et des erreurs
      url: ./app-loading-error.md
    - name: Initialisation de l'application
      url: ./app-initialization.md
    - name: Routage et navigation
      url: ./app-navigation.md
    - name: Application monopage
      url: ./routes.md
    - name: Routes imbriquées
      url: ./nested-routes.md
    - name: SSR et rendu isomorphe
      url: ./ssr.md
- name: Gestion d'état
  content:
    - name: Qu'est-ce que la gestion d'état
      url: ./state-management.md
    - name: État contextuel
      url: ./context-state.md
    - name: Requête de style
      url: ./match-var.md
- name: Production et déploiement
  url: ./build-app.md
- name: Autres composants
  content:
    - name: Injection de style hôte
      url: ./inject-host-style.md
    - name: Composant non explicite
      url: ./non-explicit-component.md
    - name: Composant replace-temp
      url: ./replace-template.md
    - name: Composant global-link
      url: ./global-link.md