- name: Einführung
  url: ./introduction.md
- name: Erste Schritte
  content:
    - name: Skript-Referenz
      url: ./script-reference.md
    - name: Erste App erstellen
      url: ./create-first-app.md
- name: Schnellstart
  url: ./quick-start.md
- name: Template-Syntax
  content:
    - name: Inhaltsrendering
      url: ./content-rendering.md
    - name: Event-Bindung
      url: ./event-binding.md
    - name: Attributreaktion
      url: ./property-response.md
    - name: Attribut-Bindung
      url: ./property-binding.md
    - name: Klassen- und Stilbindung
      url: ./class-style-binding.md
    - name: Konditionales Rendering
      url: ./conditional-rendering.md
    - name: Listen-Rendering
      url: ./list-rendering.md
    - name: Berechnete Eigenschaften
      url: ./computed-properties.md
    - name: Beobachter
      url: ./watchers.md
    - name: Lebenszyklus
      url: ./lifecycle.md
- name: Komponenten
  content:
    - name: Komponente erstellen
      url: ./create-component.md
    - name: Attribute vererben
      url: ./inherit-attributes.md
    - name: Slots
      url: ./slots.md
    - name: Tiefe Eigenschaftsbindung
      url: ./deep-property-binding.md
    - name: Benutzerdefinierte Ereignisse
      url: ./custom-events.md
- name: App und Skalierung
  content:
    - name: Micro-App
      url: ./micro-app.md
    - name: App-Konfiguration Grundlagen
      url: ./app-config-basics.md
    - name: Seitenwechsel-Animation
      url: ./page-transition-animation.md
    - name: Laden und Fehlerbehandlung
      url: ./app-loading-error.md
    - name: App-Initialisierung
      url: ./app-initialization.md
    - name: Routing und Navigation
      url: ./app-navigation.md
    - name: Single-Page-App
      url: ./routes.md
    - name: Verschachtelte Routen
      url: ./nested-routes.md
    - name: SSR und isomorphes Rendering
      url: ./ssr.md
- name: Zustandsverwaltung
  content:
    - name: Was ist Zustandsverwaltung
      url: ./state-management.md
    - name: Kontext-Zustand
      url: ./context-state.md
    - name: Stilabfrage
      url: ./match-var.md
- name: Produktion und Bereitstellung
  url: ./build-app.md
- name: Andere Komponenten
  content:
    - name: Host-Stile injizieren
      url: ./inject-host-style.md
    - name: Nicht-explizite Komponente
      url: ./non-explicit-component.md
    - name: replace-temp-Komponente
      url: ./replace-template.md