- name: Introduction
  url: ./introduction.md
- name: Getting Started
  content:
    - name: Script Reference
      url: ./script-reference.md
    - name: Create First App
      url: ./create-first-app.md
- name: Quick Start
  url: ./quick-start.md
- name: Template Syntax
  content:
    - name: Content Rendering
      url: ./content-rendering.md
    - name: Event Binding
      url: ./event-binding.md
    - name: Property Reactivity
      url: ./property-response.md
    - name: Property Binding
      url: ./property-binding.md
    - name: Class and Style Binding
      url: ./class-style-binding.md
    - name: Conditional Rendering
      url: ./conditional-rendering.md
    - name: List Rendering
      url: ./list-rendering.md
    - name: Computed Properties
      url: ./computed-properties.md
    - name: Watchers
      url: ./watchers.md
    - name: Lifecycle
      url: ./lifecycle.md
- name: Components
  content:
    - name: Create Component
      url: ./create-component.md
    - name: Inherit Attributes
      url: ./inherit-attributes.md
    - name: Slots
      url: ./slots.md
    - name: Deep Property Binding
      url: ./deep-property-binding.md
    - name: Custom Events
      url: ./custom-events.md
- name: Application & Scaling
  content:
    - name: Micro App
      url: ./micro-app.md
    - name: App Configuration Basics
      url: ./app-config-basics.md
    - name: Page Transition Animation
      url: ./page-transition-animation.md
    - name: Loading & Error Handling
      url: ./app-loading-error.md
    - name: App Initialization
      url: ./app-initialization.md
    - name: Routing & Navigation
      url: ./app-navigation.md
    - name: Single Page Application
      url: ./routes.md
    - name: Nested Routes
      url: ./nested-routes.md
    - name: SSR & Isomorphic Rendering
      url: ./ssr.md
- name: State Management
  content:
    - name: What is State Management
      url: ./state-management.md
    - name: Context State
      url: ./context-state.md
    - name: Style Query
      url: ./match-var.md
- name: Production & Deployment
  url: ./build-app.md
- name: Other Components
  content:
    - name: Inject Host Styles
      url: ./inject-host-style.md
    - name: Non-Explicit Component
      url: ./non-explicit-component.md
    - name: replace-temp Component
      url: ./replace-template.md